version: "3.8"

services:
  api:
    build: ./
    restart: always
    ports:
      - 6000:8080
    volumes:
      - memestore:/memestore

  fileserver:
    build: ./nginx
    restart: always
    ports:
      - "6001:80"
    volumes:
      - memestore:/var/www/html/img/

volumes:
  memestore:
